name: demo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#
version: 1.0.0+1

environment:
  sdk: ^3.10.0

#
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  provider: ^6.1.1
  intl: ^0.19.0
  fl_chart: ^0.66.0   # Cho biểu đồ (Giai đoạn 3)

dev_dependencies:
  flutter_test:
    sdk: flutter

  #
  flutter_lints: ^6.0.0

#
flutter:
  assets:
    - assets/books/

  #
  uses-material-design: true


